base_locale: en
locales:
  - en
  - en_GB
  - en_US
  - cs
  - de
  - es
  - fr
  - hu
  - it
  - pl
  - pt
search:
  paths:
    - app
    - config
    - lib
data:
  read:
    - config/locales/%{locale}/%{locale}.yml
    - config/locales/**/*.%{locale}.yml
  write:
    - config/locales/%{locale}/%{locale}.yml
ignore_missing:
  - 'activerecord.attributes.*.*'
  - 'datetime.*'
  - 'date.*'

